[monitor:///var/log/syslog]
index = linux
sourcetype = syslog
disabled = false

[monitor:///var/log/auth.log]
index = linux
sourcetype = linux_secure
disabled = false

[monitor:///var/log/kern.log]
index = linux
sourcetype = linux_kern
disabled = false

[monitor:///var/log/cron.log]
index = linux
sourcetype = linux_cron
disabled = false

[monitor:///var/log/dpkg.log]
index = linux
sourcetype = linux_pkg
disabled = false
