[WinEventLog://Application]
disabled = 0
index = win10

[WinEventLog://Security]
disabled = 0
index = win10

[WinEventLog://System]
disabled = 0
index = win10

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = win10

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = 0
index = win10
sourcetype = WinEventLog:PowerShell

[WinEventLog://Microsoft-Windows-Windows Defender/Operational]
disabled = 0
index = win10
sourcetype = WinEventLog:Defender
